### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

# Criar um array com 10 numeros inteiros aleatorios entre 1 e 50
arr = np.random.randint(1,51, size=10)

# Calcular a media e o desvio padrão do array
media = np.mean(arr)
desvio_padrao = np.std(arr)

print("Array: ", arr)
print("Média: ", media)
print("Desvio padrão: ", desvio_padrao)

Array:  [31  7 15 23 27 23 28 30 18 13]
Média:  21.5
Desvio padrão:  7.592759709091286


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)

# Calcular a raiz quadrada dos valores menores ou iguais a 0,5
arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

print(arr)

[0.72013533 0.80216261 0.50899321 0.81503784 0.206254   0.68546389
 0.70646943 0.67608775 0.58658509 0.51291268]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz_3D = np.random.rand(3, 3, 3)

#Exibir o valor maxima de cada linha de cada matriz 2D dentro da matriz 3D
max_valores = np.amax(matriz_3D, axis=1)


print("Matriz 3D: \n", matriz_3D)
print("Valores maiores de cada linha da matriz 3D: \n", max_valores)

Matriz 3D: 
 [[[0.27945293 0.62640283 0.14208351]
  [0.35923685 0.06554755 0.60113334]
  [0.14488723 0.14361988 0.56139319]]

 [[0.57852983 0.2721094  0.28730171]
  [0.59003224 0.56622596 0.78101903]
  [0.94469373 0.0867917  0.43784776]]

 [[0.01337515 0.95189779 0.03176053]
  [0.28929016 0.3895749  0.99340846]
  [0.2444561  0.23363901 0.41678477]]]
Valores maiores de cada linha da matriz 3D: 
 [[0.35923685 0.62640283 0.60113334]
 [0.94469373 0.56622596 0.78101903]
 [0.28929016 0.95189779 0.99340846]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)

media = np.mean(matriz, axis=1)
media_linha = matriz - media[:, np.newaxis]

print("Matriz gerada: \n", matriz)
print("Média da linha: \n", media)
print("Matriz com a media das linhas subtraidas: \n", media_linha)

Matriz gerada: 
 [[0.04153997 0.79644241 0.32058746 0.2942229  0.33290784]
 [0.15563802 0.40784455 0.62347397 0.12988852 0.8491952 ]
 [0.80189014 0.56949993 0.3832177  0.51506825 0.40012952]
 [0.60895375 0.55753935 0.16774843 0.34254743 0.72362329]
 [0.73503773 0.69301451 0.22030873 0.27125369 0.48727746]]
Média da linha: 
 [0.35714012 0.43320805 0.53396111 0.48008245 0.48137842]
Matriz com a media das linhas subtraidas: 
 [[-0.31560015  0.43930229 -0.03655265 -0.06291722 -0.02423228]
 [-0.27757003 -0.02536351  0.19026592 -0.30331953  0.41598715]
 [ 0.26792904  0.03553882 -0.15074341 -0.01889286 -0.13383158]
 [ 0.1288713   0.0774569  -0.31233402 -0.13753502  0.24354084]
 [ 0.2536593   0.21163608 -0.26106969 -0.21012473  0.00589904]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np
matriz = np.random.rand(4,4)

diagonal_principal = np.diag(matriz)
diagonal_secundaria = np.diag(np.fliplr(matriz))
media_diagonal = np.mean([diagonal_principal, diagonal_secundaria])
std_diagonal = np.std([diagonal_principal, diagonal_secundaria])

print("Matriz original: \n", matriz)
print("Diagonal Princial: \n", diagonal_principal)
print("Diagonal Secundária: \n", diagonal_secundaria)
print("Media da Diagonal: \n", media_diagonal)
print("Desvio Padrão: \n", std_diagonal)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-1185938917757657> in <cell line: 4>()
      2 matriz = np.random.rand(4,4)
      3 
----> 4 diagonal_principal = np.diag(matriz)
      5 diagonal_secundaria = np.diag(np.fliplr(matriz))
      6 media_diagonal = np.mean([diagonal_principal, diagonal_secundaria])

TypeError: 'numpy.ndarray' object is not callable